### PR TITLE
Get preprocessing, reloading of preprocessed datasets, report, etc up and going

### PR DESCRIPTION
**Pull request by NJManganelli**
See title

### CODE REVIEW

**Comment by NJManganelli** [comment]
There's an error in the main processor perhaps that leads to incompatible broadcasting of shapes. It could also be an error in coffea/awkward/dask, but I'll have to defer debugging it to someone else

**Comment by NJManganelli** [comment]
Can run with parallel workers in a LocalCluster by passing option `-ncores 8`; then after the json.gz files are created for preprocessed filesets, you can just load them the next time instead of redoing the preprocessing, with the `--preprocessed` flag

**Comment by yhaddad** [comment]
@NJManganelli  I have tried running this code and I got the following error at the very end:

```
Traceback (most recent call last):
  File "/afs/cern.ch/user/y/yhaddad/.local/lib/python3.9/site-packages/dask/highlevelgraph.py", line 569, in get_all_external_keys
    return self._all_external_keys
AttributeError: 'HighLevelGraph' object has no attribute '_all_external_keys'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/afs/cern.ch/work/y/yhaddad/CMSDAS-MonoZ-Tutorial-2024/processing/run-process-local.py", line 173, in <module>
    main()
  File "/afs/cern.ch/work/y/yhaddad/CMSDAS-MonoZ-Tutorial-2024/processing/run-process-local.py", line 151, in main
    (histograms, report) = dask.compute(event_compute, rep_compute)
  File "/afs/cern.ch/user/y/yhaddad/.local/lib/python3.9/site-packages/dask/base.py", line 654, in compute
    dsk = collections_to_dsk(collections, optimize_graph, **kwargs)
  File "/afs/cern.ch/user/y/yhaddad/.local/lib/python3.9/site-packages/dask/base.py", line 427, in collections_to_dsk
    dsk = opt(dsk, keys, **kwargs)
  File "/afs/cern.ch/user/y/yhaddad/.local/lib/python3.9/site-packages/dask_awkward/lib/optimize.py", line 54, in all_optimizations
    dsk = dsk.cull(set(keys))  # type: ignore
  File "/afs/cern.ch/user/y/yhaddad/.local/lib/python3.9/site-packages/dask/highlevelgraph.py", line 726, in cull
    all_ext_keys = self.get_all_external_keys()
  File "/afs/cern.ch/user/y/yhaddad/.local/lib/python3.9/site-packages/dask/highlevelgraph.py", line 576, in get_all_external_keys
    keys.update(layer.get_output_keys())
  File "/afs/cern.ch/user/y/yhaddad/.local/lib/python3.9/site-packages/dask/blockwise.py", line 487, in get_output_keys
    *[range(self.dims[i]) for i in self.output_indices]
  File "/afs/cern.ch/user/y/yhaddad/.local/lib/python3.9/site-packages/dask/blockwise.py", line 487, in <listcomp>
    *[range(self.dims[i]) for i in self.output_indices]
  File "/afs/cern.ch/user/y/yhaddad/.local/lib/python3.9/site-packages/dask/blockwise.py", line 447, in dims
    self._dims = _make_dims(self.indices, self.numblocks, self.new_axes)
  File "/afs/cern.ch/user/y/yhaddad/.local/lib/python3.9/site-packages/dask/blockwise.py", line 1484, in _make_dims
    dims = broadcast_dimensions(indices, numblocks)
  File "/afs/cern.ch/user/y/yhaddad/.local/lib/python3.9/site-packages/dask/blockwise.py", line 1475, in broadcast_dimensions
    raise ValueError("Shapes do not align %s" % g)
ValueError: Shapes do not align {'.0': {1, 2, 3, 4, 5, 7, 10, 12, 14, 15, 16, 17, 18, 19, 20, 22, 23, 24, 27, 29, 32, 33, 40, 41, 45, 50, 54, 56, 57, 60, 63, 67, 69, 74, 81, 83, 90, 93, 99, 115}}
```

Any idea what the issue?

**Comment by NJManganelli** [comment]
No, that was the issue I couldn't figure out

**Comment by yhaddad** [comment]
I am checking the files, it seems that ell of them have eventies and have events. So it must be something else. We need to debug this quick before we get started.

**Comment by yhaddad** [comment]
The issues imanate from the HLT_* branches. These are not the same accross all the file of a given datasets. Which is something that we have observed in the previous version of NanoAOD pre-legacy. I made a little workaround to pre-process the rootfiles and removes the HLT_* paths from the tres as these are not needed for this tutorial. I should commit a change soon!

**Pull request merged**
